### ISSUE TITLE
Iterm2主题颜色的问题

### ISSUE THREAD

**Issue by xiejun** [Aaaaaashu/Mac-dev-setup#5]
Iterm2设置了Solarized主题，但是有些地方没有像你贴图里那样高亮显示，还需要设置什么东西吗
![image](https://cloud.githubusercontent.com/assets/1418991/8822579/07374b66-3099-11e5-814d-8083656510fe.png)
![image](https://cloud.githubusercontent.com/assets/1418991/8822684/cfc5efc4-3099-11e5-938c-699f13ca77dd.png)
装了oh my zsh后，使用pygmalion主题后也没有什么高亮效果
![image](https://cloud.githubusercontent.com/assets/1418991/8822870/080046f4-309b-11e5-80af-c1ac7c7c30dc.png)

**Comment by Aaaaaashu** [comment]
在 .zshrc 里頭加一下
```
export LSCOLORS="exfxcxdxbxexexabagacad"
alias ls='ls -G'
```
